CC = gcc
CFLAGS = -Wall -Wextra -g -fsanitize=address
LDFLAGS = -lssl -lcrypto
SOURCES = $(wildcard server/*.c)                
OBJECTS = $(SOURCES:.c=.o)

all: world

run: world
	ASAN_OPTIONS=detect_leaks=1 ./world

world: $(OBJECTS)
	$(CC) $(CFLAGS) -o world $(OBJECTS) $(LDFLAGS)

clean:
	rm -f world server/*.o